### ISSUE TITLE
Support for C++ / .Net Core Project types

### ISSUE THREAD

**Issue by Hecatron** [dbarsam/python-vsgen#12]
I've had a look through the source and noticed there's currently only a plugin for generating python tools for visual studio type projects

I was wondering if there's any plans for plugins to support the new .csproj files used with .Net Core
or .csproj files used with C++.
The reason being, is that I was thinking of looking into writing some if they didn't already exist for use with Scons (via the use of separate scons builder class's), similar to the way cmake generates Visual Studio project files.

**Comment by dbarsam** [comment]
There's been no real plans; my main focus is presently on Python.

However, it would be interesting if there was another vsgen plugin apart from python one.  If you want to try it out, then go for it.

**Comment by Hecatron** [comment]
Okay, closing for now since I need to think about fitting into a Scons builder
